//! What kind of place a zone is.
//!
//! A breach used to change numbers and nothing else: `WorldMap::new(seed)`
//! took a seed and nothing more, so a zone-7 sector was generated by exactly
//! the same rules as zone 1. A `SectorDef` is what makes a zone somewhere —
//! it shifts where `WorldMap::classify`'s biome boundaries fall, and its
//! look, its roster and where it can be built all fall out of that one
//! change: `Game::habitat_pools` filters species by the tile's biome, and
//! `Biome::walkable` gates every placement in the game.
//!
//! **Fully data-driven.** Everything a sector *is* lives in
//! `assets/sectors/*.ron`; nothing here names a shipped one. A mod adds a
//! sector by dropping in a file, and **deleting the directory restores
//! today's game exactly** — the same supported way to play that deleting
//! `assets/affixes/` or `assets/policies/enemy_battle.ron` is.
//!
//! **Which sector a zone gets is derived, never stored.** It is a function
//! of the world seed and the zone number, both already saved, so it survives
//! a reload with no `SAVE_FORMAT_VERSION` bump and no cache. If you ever
//! find yourself adding a save field or a cache for a sector, something has
//! started reading run state it shouldn't.

use std::collections::BTreeMap;
use std::path::Path;

use bevy_ecs::prelude::Resource;
use serde::{Deserialize, Serialize};

use crate::tuning::MIN_SECTOR_WALKABLE_FRACTION;
use crate::world::{SectorShape, WorldMap};

/// The hue every walkable biome's colour is measured against, in degrees.
///
/// The renderer spreads the five walkable biomes across a range around this
/// anchor — OpenGrid sits 30 degrees below it, Platform 48 above — and a
/// sector moves the whole band by moving the anchor. So this is not "the
/// colour of ground": it is the origin the band rotates about, which is what
/// makes the neutral palette reproduce the shipped table exactly rather than
/// approximately.
///
/// It lives here rather than in `tuning.rs` because it is the schema of the
/// `palette` field directly below it, not a difficulty knob. `crates/gui`
/// reads it as the rotation origin — a call rather than a copy, since a gui
/// that hardcoded its own origin would silently reskin the neutral game.
pub const NEUTRAL_GROUND_HUE: f32 = 180.0;

/// The same anchor for the two biomes that are holes in the map.
pub const NEUTRAL_HAZARD_HUE: f32 = 20.0;

/// The band a ground hue must sit in, in degrees.
///
/// Not a matter of taste. The map's one load-bearing promise is that **hue
/// answers "can I cross this"** (see `biome_tint` in
/// `crates/gui/src/render/base.rs`), and these bounds are how wide the band
/// can swing before a walkable biome starts reading as hostile once the
/// per-biome spread is added back on. `every_biomes_tint_says_whether_it_
/// can_be_walked_on` sweeps this whole range against every biome, so a
/// widened band fails there rather than shipping a map that tells the player
/// they may walk into the void.
pub const GROUND_HUE_BAND: (f32, f32) = (150.0, 240.0);

/// The same bound for the hazard band, which must stay hot.
pub const HAZARD_HUE_BAND: (f32, f32) = (0.0, 40.0);

/// A string newtype for the reason `ItemId` and `AffixId` are: a sector is
/// content, so a mod must be able to add one without touching Rust. `Ord`
/// so the pool `for_zone` indexes into is in the same order every run
/// whatever order the files come off the disk.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SectorId(pub String);

impl SectorId {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for SectorId {
    fn from(s: &str) -> Self {
        SectorId(s.to_string())
    }
}

/// How far a sector moves each of `classify`'s thresholds.
///
/// A **delta** rather than an absolute, so a file names only the numbers it
/// cares about and everything else stays neutral. That is what lets a whole
/// sector be authored as one line, and it means a future sixth threshold
/// doesn't invalidate every shipped file.
#[derive(Clone, Copy, Debug, Default, Serialize, Deserialize)]
pub struct ShapeDelta {
    #[serde(default)]
    pub void_elevation: f64,
    #[serde(default)]
    pub black_ice_elevation: f64,
    #[serde(default)]
    pub static_temperature: f64,
    #[serde(default)]
    pub null_temperature: f64,
    #[serde(default)]
    pub null_moisture: f64,
    #[serde(default)]
    pub mainframe_moisture: f64,
}

/// Where a sector puts the two colour bands, in degrees.
///
/// Two numbers rather than seven authored colours, because the renderer's
/// rule leaves no freedom worth having: hue says whether ground can be
/// crossed, and the spread *within* each band is what tells the biomes
/// apart. Moving the bands is the whole of what a palette may do.
#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub struct SectorPalette {
    pub ground_hue: f32,
    pub hazard_hue: f32,
}

impl Default for SectorPalette {
    fn default() -> Self {
        SectorPalette {
            ground_hue: NEUTRAL_GROUND_HUE,
            hazard_hue: NEUTRAL_HAZARD_HUE,
        }
    }
}

/// One sector as authored. See `assets/sectors/README.md` for the schema.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SectorDef {
    pub id: SectorId,
    /// Announced on the breach line, so the player learns where they landed
    /// rather than only how hard it is.
    pub name: String,
    /// The sentence under the name on that same line.
    pub description: String,
    #[serde(default)]
    pub shape: ShapeDelta,
    #[serde(default)]
    pub palette: SectorPalette,
}

impl SectorDef {
    /// This sector's thresholds: its deltas applied on top of `NEUTRAL`.
    pub fn shape(&self) -> SectorShape {
        let n = SectorShape::NEUTRAL;
        let d = self.shape;
        SectorShape {
            void_elevation: n.void_elevation + d.void_elevation,
            black_ice_elevation: n.black_ice_elevation + d.black_ice_elevation,
            static_temperature: n.static_temperature + d.static_temperature,
            null_temperature: n.null_temperature + d.null_temperature,
            null_moisture: n.null_moisture + d.null_moisture,
            mainframe_moisture: n.mainframe_moisture + d.mainframe_moisture,
        }
    }

    /// Why this file is unusable, or `None` if it is fine.
    ///
    /// Checked at load so a bad sector is skipped with a warning rather than
    /// reaching `enter_next_zone`, which has no way to refuse: by then the
    /// old map is gone and a sector with no ground has already stranded the
    /// run.
    pub fn fault(&self) -> Option<String> {
        if self.id.as_str().is_empty() {
            return Some("has an empty id".into());
        }
        if self.name.is_empty() || self.description.is_empty() {
            return Some(
                "has no name or no description, so a breach into it would announce a blank line"
                    .into(),
            );
        }
        let (glo, ghi) = GROUND_HUE_BAND;
        if !(glo..=ghi).contains(&self.palette.ground_hue) {
            return Some(format!(
                "has a ground hue of {} degrees, outside the cool band {glo}..={ghi} — \
                 walkable ground must not read as hostile",
                self.palette.ground_hue
            ));
        }
        let (hlo, hhi) = HAZARD_HUE_BAND;
        if !(hlo..=hhi).contains(&self.palette.hazard_hue) {
            return Some(format!(
                "has a hazard hue of {} degrees, outside the warm band {hlo}..={hhi} — \
                 a hole in the map must read as hostile",
                self.palette.hazard_hue
            ));
        }
        let fraction = walkable_fraction(self.shape());
        if fraction < MIN_SECTOR_WALKABLE_FRACTION {
            return Some(format!(
                "leaves only {:.0}% walkable ground, under the floor of {:.0}% — \
                 a party would have nowhere to spawn, build or place a Stack link",
                fraction * 100.0,
                MIN_SECTOR_WALKABLE_FRACTION * 100.0
            ));
        }
        None
    }
}

/// Seeds the walkable-ground sample is taken across.
///
/// Three rather than one because a shape that happens to leave ground in one
/// world is not evidence it leaves ground in every world, and a sector is
/// rolled against whatever seed the run has. Fixed values so the verdict is
/// the same on every machine and in every run.
const WALKABLE_SAMPLE_SEEDS: [u32; 3] = [4242, 7, 90210];

/// How far the sample reaches from the origin, in tiles.
///
/// Around the origin specifically, because that is where `find_walkable_
/// start` looks and therefore where a zone's play actually happens.
const WALKABLE_SAMPLE_RADIUS: i32 = 32;

/// The fraction of ground a shape leaves standable, taken as the **worst**
/// of the sample worlds rather than the mean: the floor is a safety property,
/// and a sector that strands one run in three has not passed.
fn walkable_fraction(shape: SectorShape) -> f64 {
    let r = WALKABLE_SAMPLE_RADIUS;
    let total = ((r * 2) * (r * 2)) as f64;
    WALKABLE_SAMPLE_SEEDS
        .into_iter()
        .map(|seed| {
            let mut map = WorldMap::with_shape(seed, shape);
            let walkable = (-r..r)
                .flat_map(|y| (-r..r).map(move |x| (x, y)))
                .filter(|&(x, y)| map.tile(x, y).walkable)
                .count();
            walkable as f64 / total
        })
        .fold(f64::INFINITY, f64::min)
}

/// Every sector the game knows about, loaded from `assets/sectors/`.
///
/// **An empty database is valid and inert**: no zone can be handed a
/// sector, so `WorldMap` is built at `SectorShape::NEUTRAL` everywhere and
/// the game is exactly the pre-sector one.
#[derive(Resource, Default)]
pub struct SectorDb {
    /// A `BTreeMap` rather than a `HashMap` because the derivation indexes
    /// into this pool by position. A hash order would hand the same
    /// `(seed, zone)` a different sector between runs, which is the one
    /// thing deriving rather than storing exists to prevent.
    defs: BTreeMap<SectorId, SectorDef>,
}

impl SectorDb {
    /// Follows every other `load_dir` in the crate: a malformed or unusable
    /// file is skipped with a warning the game logs at startup, never a
    /// panic that stops a player reaching the main menu over somebody else's
    /// mod.
    pub fn load_dir(dir: &Path) -> std::io::Result<(Self, Vec<String>)> {
        let mut db = SectorDb::default();
        let mut warnings = Vec::new();
        // A missing directory is not an error: sectors are optional content
        // and an install without them is the pre-sector game.
        let entries = match std::fs::read_dir(dir) {
            Ok(entries) => entries,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok((db, warnings)),
            Err(e) => return Err(e),
        };
        for entry in entries {
            let path = entry?.path();
            if path.extension().and_then(|e| e.to_str()) != Some("ron") {
                continue;
            }
            let text = std::fs::read_to_string(&path)?;
            match ron::from_str::<SectorDef>(&text) {
                Ok(def) => match def.fault() {
                    Some(why) => {
                        warnings.push(format!("skipped invalid sector file {path:?}: {why}"))
                    }
                    None => {
                        db.defs.insert(def.id.clone(), def);
                    }
                },
                Err(e) => warnings.push(format!("skipped invalid sector file {path:?}: {e}")),
            }
        }
        Ok((db, warnings))
    }

    pub fn get(&self, id: &SectorId) -> Option<&SectorDef> {
        self.defs.get(id)
    }

    /// Every sector, in id order — which is the order `for_zone` indexes.
    pub fn all(&self) -> impl Iterator<Item = &SectorDef> {
        self.defs.values()
    }
}
